### ISSUE TITLE
counters stuck on value at sunset

### ISSUE THREAD

**Issue by Bassie007** [ProudElm/solaredgeoptimizers#15]
[home-assistant.log](https://github.com/ProudElm/solaredgeoptimizers/files/10231382/home-assistant.log)
Hi, at sunset, all values of all individual panels remain stuck at a value (eg 1.04 w) and a new update will not be released until the next day
so it is difficult to recognize if there is nothing more generated by the respective panel
does something go wrong in my HA environment and should it just end on 0w /unknow because there will be no more update
or is this a feature by design?
![ha-optimizer1](https://user-images.githubusercontent.com/116219637/207702948-c53a3ec2-055c-40db-95e2-f730e195ffce.jpg)
![ha-optimizer2](https://user-images.githubusercontent.com/116219637/207702954-5800b579-b063-4412-a844-1f523616bbe5.jpg)

**Comment by ProudElm** [comment]
Hi, this is a problem caused by the solaredge portal. Once the inverter is no longer 'on' the data is no longer refreshed. Meaning the last value of the day will be sent even through the night untill the inverter gets started again and restart reporting values.

A possible solution i'm working on is that i'm checking the last update value and if this is longer then eq 1 hour i set all the relevant values to 0. But yeah, i'm still working on it..

**Comment by Dutchy-79** [comment]
Same here, all values are stuck end of the day.
![Screenshot_20230110_082732_Home Assistant](https://user-images.githubusercontent.com/22749572/211488521-bc5a618b-c6bf-4dc9-882d-74dd6287fa56.png)

V1.1.3 installed

**Comment by ProudElm** [comment]
I have resolved this issue by checking the last measurement value and if this is older then 1 hour, the sensors values are set to 0.

**Comment by Bassie007** [comment]
great job 👍
